application: application_id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /images
  static_dir: frontend/images
  secure: always
- url: /js
  static_dir: frontend/js
  secure: always
- url: /css
  static_dir: frontend/css
  secure: always
- url: /font
  static_dir: frontend/fonts
  secure: always
- url: /tasks/.*
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
